---

- hosts: all
  become: true
  tasks:

   - name: "Configure host name"
     hostname:
        name: "{{ inventory_hostname }}"
     tags: dns

   - name: "Generate /etc/hosts file"
     template:
       src: etc/hosts.j2
       dest: /etc/hosts
     tags: dns

   - name: "Install NTP service"
     yum:
       name: chrony
       state: installed
     tags: ntp

   - name: "Make sure NTP is started up"
     systemd:
       name: chronyd
       enabled: yes
       state: restarted
     tags: ntp

   - name: "Enable the OpenStack repository"
     yum:
       name: centos-release-openstack-ocata
       state: installed
     tags: upgrade

   - name: "Upgrade all packages"
     yum: name=* state=latest
     tags: upgrade

   - name: "Check for reboot hint"
     shell: |
        LAST_KERNEL=$(rpm -q --last kernel | awk 'NR==1{sub(/kernel-/,""); print $1}')
        CURRENT_KERNEL=$(uname -r); if [ $LAST_KERNEL != $CURRENT_KERNEL ]; then
          echo 'reboot'
        else
          echo 'no'
        fi
     ignore_errors: true
     register: reboot_hint
     tags: upgrade

   - name: "Reboot {{ inventory_hostname }} node"
     shell: >
       sleep 2 &&
       shutdown -r +1 "Reboot required to update kernel."
     async: 1
     poll: 0
     ignore_errors: true
     when: reboot_hint.stdout.find("reboot") != -1
     tags: upgrade

   - name: "Waiting for {{ inventory_hostname }} node to come back..."
     local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=300
     become: false
     when: reboot_hint.stdout.find("reboot") != -1
     tags: upgrade

   - name: "Install OpenStack client"
     yum:
       name: python-openstackclient,openstack-selinux
       state: installed


- hosts: control
  become: true
  tasks:
    
   - name: "Install MariaDB service"
     yum:
       name: mariadb,mariadb-server,python2-PyMySQL 
       state: installed

   - name: "Make sure the MariaDB service is stopped"
     systemd:
       name: mariadb
       state: stopped

   - name: "Get management interface IP"
     shell: >
       ifconfig eth1 | awk '/\sinet\s/{print $2}'
     register: get_management_ip

   - name: "Enable access to database via the management network"
     template:
       src: etc/my.cnf.d/openstack.cnf.j2
       dest: /etc/my.cnf.d/openstack.cnf

   - name: "Set MariaDB root password"
     shell: |
       set -exu
       mysqld_safe --skip-grant-tables --skip-networking &
       server_pid=$!
       echo -e "
         FLUSH PRIVILEGES;
         SET PASSWORD FOR 'root'@'localhost' = PASSWORD('1234');
         " | mysql -u root
       kill "${server_pid}"

   - name: "Start and enable the MariaDB service"
     systemd:
       name: mariadb
       enabled: yes
       state: started

   - name: "Enter root password for MariaDB service"
     shell: >
       echo 1234 | mysql_secure_installation
