---
- hosts: target
  become: true

  vars:
    user: stack
    home: "/home/{{ user }}"

  tasks:

    - name: Create libvirt group
      group:
        name: libvirt
        state: present

    - name: Create {{ user }} user
      user:
        name: "{{ user }}"
        groups: "libvirt"

    - name: Create ~/.ssh directory
      file:
        path: "{{ home }}/.ssh"
        mode: 0700
        state: directory
        owner: "{{ user }}"

    - name: Create ~/.ssh/authorized_keys file
      file:
        path: "{{ home }}/.ssh/authorized_keys"
        mode: 0600
        state: touch
        owner: "{{ user }}"

    - name: Add SSH key to {{ user }} user
      lineinfile: 
        path: "{{ home }}/.ssh/authorized_keys"
        line: "{{ lookup('env','TARGET_PUB_KEY') }}"

    - name: Install packages to use libvirt
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - gcc
        - libvirt
        - libvirt-devel
        - qemu
        - qemu-kvm

    - name: Start and enable the libvirtd service
      systemd:
        name: libvirtd
        enabled: yes
        state: started

    - name: Install rsync tool
      yum:
        name: rsync
        state: present

    - name: Get vagrant RPM
      get_url:
        url: "https://releases.hashicorp.com/vagrant/2.0.1/vagrant_2.0.1_x86_64.rpm"
        dest: /tmp/vagrant_2.0.1_x86_64.rpm

    - name: Install vagrant
      yum:
        name: /tmp/vagrant_2.0.1_x86_64.rpm
        state: present

    - name: Install livirt vagrant plugin
      command:
        vagrant plugin install vagrant-libvirt

    - name: Check to see if pip is already installed
      command: "pip --version"
      ignore_errors: true
      register: pip_is_installed
      changed_when: false

    - name: Set up PIP
      when: pip_is_installed.rc != 0
      block:

        - name: download get-pip.py
          get_url:
            url: https://bootstrap.pypa.io/get-pip.py
            dest: /tmp

        - name: install pip
          command: "python /tmp/get-pip.py"

        - name: delete get-pip.py
          file:
            path: /tmp/get-pip.py
            state: absent

    - name: Install ansible
      pip:
        name: ansible
