---
- hosts: target
  
  vars:
    user: stack
    home: "/home/{{ user }}"

  tasks:

   - name: "Create {{ user }} user"
     become: true
     user:
       name: "{{ user }}"
       groups: "libvirt"

   - name: "Create ~/.ssh directory"
     become: true
     file:
       path: "{{ home }}/.ssh"
       mode: 0700
       state: directory
       owner: "{{ user }}"

   - name: "Create ~/.ssh/authorized_keys file"
     become: true
     file:
       path: "{{ home }}/.ssh/authorized_keys"
       mode: 0600
       state: touch
       owner: "{{ user }}"

   - name: "Add SSH key to {{ user }} user"
     become: true
     lineinfile: 
       path: "{{ home }}/.ssh/authorized_keys"
       line: "{{ lookup('env','TARGET_PUB_KEY') }}"

   - name: "Install packages to use libvirt"
     become: true
     yum:
       name: "{{ item }}"
       state: present
     with_items:
       - gcc
       - libvirt
       - libvirt-devel
       - qemu
       - qemu-kvm

   - name: "Start and enable the libvirtd service"
     systemd:
       name: libvirtd
       enabled: yes
       state: started
